# https://taskfile.dev

version: "3"

dotenv:
  - .env

tasks:
  default:
    cmds:
      - echo "$PYTHON"
      - echo "$WEBUI"
      - echo "$UV_PYTHON"
    silent: true

  launch:
    dir: "{{.WEBUI}}"
    cmds:
      - "{{.PYTHON}} launch.py --xformers --api"
    silent: true

  lint:
    cmds:
      - pre-commit run -a

  update:
    cmds:
      - "{{.PYTHON}} -m uv pip install -U ultralytics mediapipe ruff pre-commit black devtools pytest"

  update-torch:
    cmds:
      - "{{.PYTHON}} -m uv pip install -U torch torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable.html"
