# https://taskfile.dev

version: "3"

dotenv:
  - .env

tasks:
  default:
    cmds:
      - echo "$PYTHON"
      - echo "$WEBUI"
    silent: true

  launch:
    dir: "{{.WEBUI}}"
    cmds:
      - "{{.PYTHON}} launch.py --xformers --api {{ .CLI_ARGS }}"
    silent: true

  lint:
    cmds:
      - pre-commit run -a

  update:
    cmds:
      - "{{.PYTHON}} -m uv pip install -U ultralytics mediapipe ruff pre-commit-uv black devtools pytest hypothesis"

  update-torch:
    cmds:
      - "{{.PYTHON}} -m uv pip install -U torch torchvision torchaudio xformers --extra-index-url https://download.pytorch.org/whl/cu126"
