name: Publish to PyPI
on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: test
    uses: ./.github/workflows/test.yml

  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: [test]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheel
        run: pipx run build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
